Load the feature attributions

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from pathlib import Path

warnings.filterwarnings('ignore')

path = Path("results")

df = pd.read_csv(path / "200_feature_attributions.csv", dtype={"ig_token": str})

df["ig_token"] = df["ig_token"].fillna("[EMPTY]")

explainer_result_cols = [
    "sv_value",
    "ig_value",
    "gpt_index_value",
    "gpt_index_word_value",
]
print("Original DataFrame:")
display(df.head())

df["gpt_index_value"] = df["gpt_index_value"] * -1
df["gpt_index_word_value"] = df["gpt_index_word_value"] * -1

print("DataFrame after sign inversion:")
display(df.head())

Original DataFrame:

,Unnamed: 0,id,dataset,sv_value,sv_token,sv_base_value,ig_value,ig_token,ig_base_value,gpt_index_value,gpt_index_word_value
0,670470,30685546,train,-0.002235,Wireless,-0.843256,-0.044053,wireless,-1.049297,0.0035,0.015
1,670471,30685546,train,0.005878,and,-0.843256,-0.003780,and,-1.049297,0.0028,0.005
2,670472,30685546,train,-0.000972,continuous,-0.843256,-0.004581,continuous,-1.049297,0.0023,0.008
3,670473,30685546,train,-0.000972,monitoring,-0.843256,0.002719,monitoring,-1.049297,0.0031,0.002
4,670474,30685546,train,-0.000972,of,-0.843256,0.010749,of,-1.049297,0.0027,0.012

DataFrame after sign inversion:

,Unnamed: 0,id,dataset,sv_value,sv_token,sv_base_value,ig_value,ig_token,ig_base_value,gpt_index_value,gpt_index_word_value
0,670470,30685546,train,-0.002235,Wireless,-0.843256,-0.044053,wireless,-1.049297,-0.0035,-0.015
1,670471,30685546,train,0.005878,and,-0.843256,-0.003780,and,-1.049297,-0.0028,-0.005
2,670472,30685546,train,-0.000972,continuous,-0.843256,-0.004581,continuous,-1.049297,-0.0023,-0.008
3,670473,30685546,train,-0.000972,monitoring,-0.843256,0.002719,monitoring,-1.049297,-0.0031,-0.002
4,670474,30685546,train,-0.000972,of,-0.843256,0.010749,of,-1.049297,-0.0027,-0.012

Flip the sign for the attributions generated by GPT

In [4]:
# def main(start_index: int, num=1000):
from tqdm import tqdm
import json
from pathlib import Path
import workers
import warnings
import pandas as pd
import os

warnings.filterwarnings("ignore")

dfs_by_id = {key: value for key, value in df.groupby("id")}
cols = ["gpt_index_value", "gpt_index_word_value"]

out_dir = Path("results") / "200_pc_per_token_gpt_flipped"
out_dir.mkdir(parents=True, exist_ok=True)
# print("Indexes:")
# print(start_index, end_index-1)
ids = list(sorted(dfs_by_id.keys()))

output = []

# for each instance
for id in tqdm(ids):
    output.append({"id": id})

    # for each explainer
    for col in cols:
        # print(col)
        pc_pos, tokens_pos, pc_neg, tokens_neg = workers.compute_aopc_separate(
            (id, dfs_by_id[id], col)
        )
        df_temp = pd.DataFrame(
            {"index": list(range(len(pc_pos))), "token": tokens_pos, "pc_value": pc_pos}
        )
        df_temp.to_csv(out_dir / f"{id}_{col}_pos.csv", index=False)

        df_temp = pd.DataFrame(
            {"index": list(range(len(pc_neg))), "token": tokens_neg, "pc_value": pc_neg}
        )
        df_temp.to_csv(out_dir / f"{id}_{col}_neg.csv", index=False)

  0%|          | 0/200 [00:00<?, ?it/s]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  0%|          | 1/200 [00:14<47:43, 14.39s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  1%|          | 2/200 [00:24<40:01, 12.13s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  2%|▏         | 3/200 [00:34<36:32, 11.13s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  2%|▏         | 4/200 [00:39<27:29,  8.42s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  2%|▎         | 5/200 [01:02<45:13, 13.92s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  3%|▎         | 6/200 [01:26<55:28, 17.16s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  4%|▎         | 7/200 [01:41<53:27, 16.62s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  4%|▍         | 8/200 [02:01<56:06, 17.54s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  4%|▍         | 9/200 [02:14<51:43, 16.25s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  5%|▌         | 10/200 [02:28<49:12, 15.54s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  6%|▌         | 11/200 [02:36<41:54, 13.30s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  6%|▌         | 12/200 [03:00<51:39, 16.49s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  6%|▋         | 13/200 [03:18<52:25, 16.82s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  7%|▋         | 14/200 [03:20<38:34, 12.44s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  8%|▊         | 15/200 [03:41<46:28, 15.07s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  8%|▊         | 16/200 [03:51<41:38, 13.58s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  8%|▊         | 17/200 [04:03<39:45, 13.04s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
  9%|▉         | 18/200 [04:20<43:21, 14.29s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 10%|▉         | 19/200 [04:33<41:32, 13.77s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 10%|█         | 20/200 [04:36<31:17, 10.43s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 10%|█         | 21/200 [04:52<36:48, 12.34s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 11%|█         | 22/200 [05:15<45:37, 15.38s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 12%|█▏        | 23/200 [05:36<50:22, 17.08s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 12%|█▏        | 24/200 [05:51<48:14, 16.44s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 12%|█▎        | 25/200 [06:03<44:03, 15.11s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 13%|█▎        | 26/200 [06:11<38:13, 13.18s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 14%|█▎        | 27/200 [06:27<40:08, 13.92s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 14%|█▍        | 28/200 [06:41<39:33, 13.80s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 14%|█▍        | 29/200 [06:50<35:34, 12.49s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 15%|█▌        | 30/200 [07:13<44:37, 15.75s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 16%|█▌        | 31/200 [07:16<33:04, 11.74s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 16%|█▌        | 32/200 [07:28<33:30, 11.97s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 16%|█▋        | 33/200 [07:30<24:54,  8.95s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 17%|█▋        | 34/200 [07:54<37:17, 13.48s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 18%|█▊        | 35/200 [08:13<41:04, 14.94s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 18%|█▊        | 36/200 [08:32<44:30, 16.28s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 18%|█▊        | 37/200 [08:45<41:11, 15.16s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 19%|█▉        | 38/200 [09:00<41:11, 15.26s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 20%|█▉        | 39/200 [09:11<37:12, 13.87s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 20%|██        | 40/200 [09:35<44:58, 16.87s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 20%|██        | 41/200 [09:55<47:46, 18.03s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 21%|██        | 42/200 [10:14<48:23, 18.37s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 22%|██▏       | 43/200 [10:25<41:54, 16.02s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 22%|██▏       | 44/200 [10:48<46:45, 17.98s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 22%|██▎       | 45/200 [11:02<43:50, 16.97s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 23%|██▎       | 46/200 [11:20<44:16, 17.25s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 24%|██▎       | 47/200 [11:28<36:56, 14.48s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 24%|██▍       | 48/200 [11:52<43:56, 17.35s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 24%|██▍       | 49/200 [12:01<37:18, 14.82s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 25%|██▌       | 50/200 [12:13<35:13, 14.09s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 26%|██▌       | 51/200 [12:36<41:01, 16.52s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 26%|██▌       | 52/200 [12:53<41:36, 16.87s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 26%|██▋       | 53/200 [13:12<42:50, 17.49s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 27%|██▋       | 54/200 [13:36<46:54, 19.27s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 28%|██▊       | 55/200 [13:58<48:27, 20.05s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 28%|██▊       | 56/200 [14:16<47:07, 19.64s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 28%|██▊       | 57/200 [14:40<49:54, 20.94s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 29%|██▉       | 58/200 [14:50<41:36, 17.58s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 30%|██▉       | 59/200 [15:08<41:56, 17.85s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 30%|███       | 60/200 [15:25<40:28, 17.35s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 30%|███       | 61/200 [15:42<40:02, 17.29s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 31%|███       | 62/200 [15:57<38:13, 16.62s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 32%|███▏      | 63/200 [16:06<32:50, 14.39s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 32%|███▏      | 64/200 [16:16<29:51, 13.17s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 32%|███▎      | 65/200 [16:40<36:53, 16.40s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 33%|███▎      | 66/200 [16:58<37:28, 16.78s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 34%|███▎      | 67/200 [17:17<38:31, 17.38s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 34%|███▍      | 68/200 [17:39<41:13, 18.74s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 34%|███▍      | 69/200 [17:51<36:35, 16.76s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 35%|███▌      | 70/200 [18:06<35:09, 16.23s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 36%|███▌      | 71/200 [18:20<33:37, 15.64s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 36%|███▌      | 72/200 [18:29<29:20, 13.76s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 36%|███▋      | 73/200 [18:52<34:58, 16.52s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 37%|███▋      | 74/200 [19:07<33:19, 15.87s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 38%|███▊      | 75/200 [19:27<35:40, 17.12s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 38%|███▊      | 76/200 [19:51<39:37, 19.17s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 38%|███▊      | 77/200 [20:10<39:40, 19.36s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 39%|███▉      | 78/200 [20:26<36:55, 18.16s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 40%|███▉      | 79/200 [20:43<35:44, 17.73s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 40%|████      | 80/200 [21:07<39:14, 19.62s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 40%|████      | 81/200 [21:30<41:04, 20.71s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 41%|████      | 82/200 [21:49<39:52, 20.28s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 42%|████▏     | 83/200 [22:08<38:54, 19.95s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 42%|████▏     | 84/200 [22:33<41:05, 21.25s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 42%|████▎     | 85/200 [22:49<37:52, 19.76s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 43%|████▎     | 86/200 [23:04<34:39, 18.24s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 44%|████▎     | 87/200 [23:23<35:04, 18.62s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 44%|████▍     | 88/200 [23:32<29:07, 15.60s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 44%|████▍     | 89/200 [23:51<30:46, 16.63s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 45%|████▌     | 90/200 [24:07<30:12, 16.48s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 46%|████▌     | 91/200 [24:17<26:34, 14.63s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 46%|████▌     | 92/200 [24:39<30:28, 16.93s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 46%|████▋     | 93/200 [24:56<29:52, 16.76s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 47%|████▋     | 94/200 [25:13<29:46, 16.85s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 48%|████▊     | 95/200 [25:37<33:08, 18.94s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 48%|████▊     | 96/200 [25:54<31:48, 18.35s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 48%|████▊     | 97/200 [26:18<34:27, 20.08s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 49%|████▉     | 98/200 [26:34<32:21, 19.04s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 50%|████▉     | 99/200 [26:55<32:50, 19.51s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 50%|█████     | 100/200 [27:12<31:30, 18.91s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 50%|█████     | 101/200 [27:32<31:24, 19.04s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 51%|█████     | 102/200 [27:50<30:41, 18.79s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 52%|█████▏    | 103/200 [28:10<30:51, 19.08s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 52%|█████▏    | 104/200 [28:34<32:58, 20.61s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 52%|█████▎    | 105/200 [28:55<33:00, 20.85s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 53%|█████▎    | 106/200 [29:16<32:40, 20.86s/it]Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
 54%|█████▎    | 107/200 [29:35<31:23, 20.25s/it]Device set to use cuda
Device set to use cuda

Calculate AOPC for each article

In [10]:
from tqdm import tqdm
import json
import pandas as pd

import scipy.stats as stats
import numpy as np

from pathlib import Path
import pandas as pd

working_dir = Path(r"f:\rct_gpt_perturbation")

file_path = working_dir / "info.json"

if file_path.exists():
    with file_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
else:
    print(f"Error: {file_path} does not exist in {Path.cwd()}")

ids = data["id"]

out_dir = working_dir / "results" / "200_pc_per_token_gpt_flipped"

cols_mapping = {
    # "sv_value": "SHAP",
    # "ig_value": "IG",
    "gpt_index_value": "GPT-index",
    "gpt_index_word_value": "GPT-token",
}

# df = pd.read_csv(os.path.join("results", "aopc_results.csv"))

df_output_list = []

for id in ids:
    _temp_dict = {"id": id}
    for col in cols_mapping.keys():
        df_pos = pd.read_csv(out_dir / f"{id}_{col}_pos.csv")
        df_neg = pd.read_csv(out_dir / f"{id}_{col}_neg.csv")
        df_all = pd.concat([df_pos, df_neg], ignore_index=True)
        _temp_dict[f"aopc_{col}"] = df_all["pc_value"].mean()
        _temp_dict[f"aopc_pos_{col}"] = df_pos["pc_value"].mean()
        _temp_dict[f"aopc_neg_{col}"] = df_neg["pc_value"].mean()
    df_output_list.append(_temp_dict)

df_output = pd.DataFrame(df_output_list)
df_output.to_csv(working_dir / "results" / "aopc_gpt_flipped.csv", index=False)

Get mean and CI for AOPC

In [11]:
def mean_ci(series, confidence=0.95):
    series = series.dropna()  # Remove NaN values
    if len(series) == 0:  # If empty after dropping NaNs, return "NaN"
        return "NaN (NaN, NaN)"

    mean = np.mean(series)

    if len(series) == 1:  # If only one value, no confidence interval can be calculated
        return f"{mean:.3f}"

    sem = stats.sem(series)  # Standard error of the mean
    ci_range = sem * stats.t.ppf((1 + confidence) / 2.0, len(series) - 1)
    lower = mean - ci_range
    upper = mean + ci_range

    return f"{mean:.3f} ({lower:.3f}, {upper:.3f})"


df_aopc_list = []

for explainer in cols_mapping.keys():
    df_aopc_list.append(
        {
            "Explainer": cols_mapping[explainer],
            "AOPC": mean_ci(df_output[f"aopc_{explainer}"]),
            "AOPC (Positive Tokens)": mean_ci(df_output[f"aopc_pos_{explainer}"]),
            "AOPC (Negative Tokens)": mean_ci(df_output[f"aopc_neg_{explainer}"]),
        }
    )


df_aopc = pd.DataFrame(df_aopc_list)
df_aopc.to_csv(working_dir / "results" / "aopc_table_gpt_flipped.csv", index=False)
display(df_aopc)

,Explainer,AOPC,AOPC (Positive Tokens),AOPC (Negative Tokens)
0,GPT-index,"-0.019 (-0.032, -0.006)","0.032 (0.019, 0.046)","-0.046 (-0.063, -0.028)"
1,GPT-token,"-0.028 (-0.043, -0.014)","0.022 (0.011, 0.034)","-0.050 (-0.070, -0.030)"